# The following example is minimalist. The security policies
# and resource specifications are not meant to be used in production.
# Please refer to the operator documentation for recommendations on
# production settings.
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: example
spec:
  images:
    vtctld: sougou/lite:rds
    vtgate: sougou/lite:rds
    vttablet: sougou/lite:rds
    vtbackup: sougou/lite:rds
    mysqld:
      mysql56Compatible: sougou/lite:rds
    mysqldExporter: prom/mysqld-exporter:v0.11.0
  cells:
  - name: useast2
    gateway:
      authentication:
        static:
          secret:
            name: example-cluster-config
            key: users.json
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi
  vitessDashboard:
    cells:
    - useast2
    extraFlags:
      security_policy: read-only
      proxy_tablets: "true"
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  keyspaces:
  - name: commerce
    turndownPolicy: Immediate
    partitionings:
    - custom:
        shards:
        - keyRange: {}
          databaseInitScriptSecret:
            name: example-cluster-config
            key: init_db.sql
          replication:
            enforceSemiSync: false
          tabletPools:
          - cell: useast2
            type: externalmaster
            replicas: 1
            vttablet:
              extraFlags:
                init_create_db: "true"
                db_charset: utf8mb4
                queryserver-config-pool-size: "5"
                queryserver-config-stream-pool-size: "5"
                queryserver-config-transaction-cap: "5"
              resources:
                requests:
                  cpu: 250m
                  memory: 256Mi
                limits:
                  memory: 384Mi
            externalDatastore:
              user: admin
              host: commerce0.cvp8ylo5tdcs.us-east-2.rds.amazonaws.com
              port: 3306
              database: commerce
              credentialsSecret:
                name: example-cluster-config
                key: db_creds.json
  updateStrategy:
    type: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: example-cluster-config
type: Opaque
stringData:
  users.json: |
    {
      "user": [{
        "UserData": "user",
        "Password": ""
      }]
    }
  db_creds.json: |
    {
      "admin": ["admin123"]
    }
  init_db.sql: |
    # Empty
